# Custom Language File for Launcher Customizer

[ejs.app]
title = "RM Launcher"

[ejs.landing]
mediaWebsiteURL = "https://rmkuran.pages.dev"
mediaXURL = "https://x.com/RMkuran"
mediaInstagramURL = "https://www.instagram.com/shouta.12.12"
mediaYouTubeURL = "https://www.youtube.com/@RMkuran"
mediaDiscordURL = "https://discord.gg/8R3qKeHND2"

[ejs.settings]
sourceGithubLink = "https://github.com/RMkuran/RMLauncher"
supportLink = "https://github.com/RMkuran/RMLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO RMLAUNCHER"
welcomeDescription = "RMによるRMのためのMinecraftランチャーです。"
welcomeDescCTA = "数クリックでゲームを開始できます。"
